# Ruff configuration
line-length = 79

[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "W",  # pycodestyle warnings
    "I",  # isort (import sorting)
    "N",  # pep8-naming
    "UP", # pyupgrade (suggests modern Python syntax)
    "PL", # pylint rules
    "RUF", # ruff-specific rules
]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
